# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-21 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taobao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(default=0)),
                ('goods_id', models.CharField(max_length=10)),
                ('goods_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('goods_Stock', models.IntegerField(default=100)),
                ('sales_Volume', models.IntegerField(default=0)),
            ],
        ),
    ]
