# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-21 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taobao', '0002_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_introduce',
            field=models.CharField(default='', max_length=250),
        ),
    ]
