# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-21 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taobao', '0003_goods_goods_introduce'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
