# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taobao', '0005_cartid_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cartId',
        ),
        migrations.AddField(
            model_name='user',
            name='num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
