# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taobao', '0006_auto_20170622_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart_id',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
