# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taobao', '0007_auto_20170622_2156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cartItem',
        ),
    ]
