# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taobao', '0008_delete_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantuty', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('goods_id', models.CharField(max_length=10)),
                ('username', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
