# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taobao', '0009_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='sum',
            field=models.IntegerField(default=0),
        ),
    ]
