# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taobao', '0010_cartitem_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='sum',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
