# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taobao', '0011_auto_20170623_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('total', models.IntegerField(default=0)),
                ('num', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
