# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taobao', '0012_auto_20170721_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='goods_id',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='goods',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='goods_set', to='taobao.goods'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantuty',
            field=models.IntegerField(default=1, verbose_name='商品数量'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='sum',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总计'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='username',
            field=models.CharField(default='', max_length=50, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.IntegerField(default=0, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_Stock',
            field=models.IntegerField(default=100, verbose_name='商品库存'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_id',
            field=models.CharField(max_length=10, verbose_name='商品ID'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_introduce',
            field=models.CharField(default='', max_length=250, verbose_name='商品简介'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_name',
            field=models.CharField(default='', max_length=100, verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品价格'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='sales_Volume',
            field=models.IntegerField(default=0, verbose_name='销量'),
        ),
        migrations.AlterField(
            model_name='user_cart',
            name='num',
            field=models.IntegerField(default=0, verbose_name='商品数量'),
        ),
        migrations.AlterField(
            model_name='user_cart',
            name='total',
            field=models.IntegerField(default=0, verbose_name='总计'),
        ),
        migrations.AlterField(
            model_name='user_cart',
            name='username',
            field=models.CharField(max_length=50, verbose_name='用户名'),
        ),
    ]
