# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pcList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processName', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('host', models.CharField(default='127.0.0.1', max_length=20)),
                ('path', models.CharField(default='/', max_length=255)),
            ],
        ),
    ]
