# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlerConsole', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pclist',
            name='logpath',
            field=models.CharField(default='/', max_length=256),
        ),
        migrations.AddField(
            model_name='pclist',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
